apiVersion: v1
kind: Service
metadata:
  name: web-administrasi-service
  labels:
    type: web-administrasi-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: http
  selector:
    app: web-administrasi
